# Generated by Django 3.2.18 on 2023-05-18 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allrelatedvideo',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='todaygenre',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='todayrelatedvideo',
            name='movie_id',
        ),
        migrations.DeleteModel(
            name='AllGenre',
        ),
        migrations.DeleteModel(
            name='AllRelatedVideo',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='TodayGenre',
        ),
        migrations.DeleteModel(
            name='TodayMovie',
        ),
        migrations.DeleteModel(
            name='TodayRelatedVideo',
        ),
    ]
