# Generated by Django 3.2.18 on 2023-05-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todayrelatedvideo',
            name='video',
            field=models.URLField(null=True),
        ),
    ]
