# Generated by Django 3.2.18 on 2023-05-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedetail',
            name='id',
        ),
        migrations.RemoveField(
            model_name='moviedetail',
            name='movie',
        ),
        migrations.AddField(
            model_name='moviedetail',
            name='movie_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
