# Generated by Django 3.2.18 on 2023-05-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20230522_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorList',
            fields=[
                ('actor', models.IntegerField(primary_key=True, serialize=False)),
                ('actor_id', models.IntegerField()),
                ('actor_name', models.CharField(max_length=1000)),
                ('actor_popularity', models.DecimalField(decimal_places=4, default=0, max_digits=1000000)),
                ('actor_revenue', models.DecimalField(decimal_places=4, default=0, max_digits=1000000)),
            ],
        ),
    ]
