# Generated by Django 3.2.18 on 2023-05-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_allmovie_eng_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allmovie',
            name='popularity',
            field=models.BigIntegerField(),
        ),
    ]
