# Generated by Django 3.2.18 on 2023-05-18 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_allmovie_popularity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allmovie',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='allmovie',
            name='updated_at',
        ),
    ]
